export default {
  ADLaMDisplay_400Regular: require('../assets/fonts/ADLaMDisplay_400Regular.ttf'),
  AbhayaLibre_400Regular: require('../assets/fonts/AbhayaLibre_400Regular.ttf'),
  AbrilFatface_400Regular: require('../assets/fonts/AbrilFatface_400Regular.ttf'),
  Aclonica_400Regular: require('../assets/fonts/Aclonica_400Regular.ttf'),
  Acme_400Regular: require('../assets/fonts/Acme_400Regular.ttf'),
  AkayaKanadaka_400Regular: require('../assets/fonts/AkayaKanadaka_400Regular.ttf'),
  AkayaTelivigala_400Regular: require('../assets/fonts/AkayaTelivigala_400Regular.ttf'),
  Cantarell_400Regular: require('../assets/fonts/Cantarell_400Regular.ttf'),
  Cantarell_700Bold: require('../assets/fonts/Cantarell_700Bold.ttf'),
  Inter_300Light: require('../assets/fonts/Inter_300Light.ttf'),
  Inter_400Regular: require('../assets/fonts/Inter_400Regular.ttf'),
  Inter_500Medium: require('../assets/fonts/Inter_500Medium.ttf'),
  Inter_600SemiBold: require('../assets/fonts/Inter_600SemiBold.ttf'),
  Inter_700Bold: require('../assets/fonts/Inter_700Bold.ttf'),
  Merriweather_700Bold: require('../assets/fonts/Merriweather_700Bold.ttf'),
  Montserrat_400Regular: require('../assets/fonts/Montserrat_400Regular.ttf'),
  Montserrat_600SemiBold: require('../assets/fonts/Montserrat_600SemiBold.ttf'),
  OpenSans_400Regular: require('../assets/fonts/OpenSans_400Regular.ttf'),
  OpenSans_500Medium: require('../assets/fonts/OpenSans_500Medium.ttf'),
  OpenSans_600SemiBold: require('../assets/fonts/OpenSans_600SemiBold.ttf'),
  OpenSans_700Bold: require('../assets/fonts/OpenSans_700Bold.ttf'),
  Poppins_400Regular: require('../assets/fonts/Poppins_400Regular.ttf'),
  Poppins_500Medium: require('../assets/fonts/Poppins_500Medium.ttf'),
  Poppins_700Bold: require('../assets/fonts/Poppins_700Bold.ttf'),
  Rubik_400Regular: require('../assets/fonts/Rubik_400Regular.ttf'),
  Rubik_700Bold: require('../assets/fonts/Rubik_700Bold.ttf'),
};
